apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: hello-remap
  namespace: openshift-logging
spec:
  inputs:
    - application:
        namespaces:
          - hello
      name: hello-logs
  pipelines:
    - inputRefs:
        - hello-logs
      name: hello-json
      outputRefs:
        - default
      parse: json
